server:
  port: 9002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://payment                   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名,集群内转发
          predicates:
#            - Path=/payment/get/**          #断言，路径相匹配的进行路由
            - Path=/**
            #After-在xx时间之后访问才有效，
            #Before-在xx时间之前访问才有效
            #Between-在xx~yy两个时间之间访问才有效
            - After=2020-04-19T16:27:26.810+08:00[Asia/Shanghai]

#        - id: payment_routh2
##          uri: http://localhost:8001
#          uri: lb://payment
#          predicates:
#            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
