###consul服务端口号
server:
  port: 8007

spring:
  application:
    name: order
  ###consul注册中心地址
  cloud:
    consul:
      host: 47.101.36.47
      port: 8500
      discovery:
        prefer-ip-address: true
#        service-name: ${spring.application.name}
